export type Course = {
  id: string; order: number; semester: 1 | 2; title: string; short: string; duration: number;
  objective: string; prerequisite: string; concepts: string[]; lessons: string[]; videoUrl: string;
}

const yt = (query: string) => `https://www.youtube.com/results?search_query=${encodeURIComponent(query)}`
const raw: Omit<Course, 'order' | 'videoUrl'>[] = [
  { id:'ensembles-nombres', semester:1, title:'Ensembles de nombres', short:'N, Z, D, Q et R', duration:55, objective:'Reconnaître, représenter et comparer les ensembles de nombres.', prerequisite:'Aucun — point de départ', concepts:['Appartenance et inclusion','Intervalles de R','Réunion et intersection','Valeur absolue et distance'], lessons:['Les ensembles N, Z, D, Q, R','Intervalles et droite graduée','Opérations sur les ensembles','Synthèse et quiz'] },
  { id:'arithmetique-n', semester:1, title:'Arithmétique dans N', short:'Divisibilité et nombres premiers', duration:70, objective:'Maîtriser division euclidienne, PGCD et nombres premiers.', prerequisite:'Ensembles de nombres', concepts:['Divisibilité','Division euclidienne','PGCD et PPCM','Décomposition en facteurs premiers'], lessons:['Multiples et diviseurs','Division euclidienne','PGCD et algorithme d’Euclide','Exercices guidés'] },
  { id:'calcul-vectoriel', semester:1, title:'Calcul vectoriel dans le plan', short:'Vecteurs et colinéarité', duration:75, objective:'Calculer avec des vecteurs et établir la colinéarité.', prerequisite:'Repérage du collège', concepts:['Égalité de vecteurs','Somme de vecteurs','Relation de Chasles','Colinéarité'], lessons:['Notion de vecteur','Somme et produit par un réel','Coordonnées','Colinéarité'] },
  { id:'projection-plan', semester:1, title:'Projection dans le plan', short:'Projections et Thalès', duration:50, objective:'Utiliser la projection pour démontrer des rapports.', prerequisite:'Calcul vectoriel', concepts:['Projection parallèle','Conservation du milieu','Théorème de Thalès','Rapports algébriques'], lessons:['Projection sur une droite','Propriétés','Thalès direct','Applications'] },
  { id:'ordre-r', semester:1, title:'Ordre dans R', short:'Comparaisons et encadrements', duration:65, objective:'Comparer, encadrer et manipuler les inégalités.', prerequisite:'Ensembles de nombres', concepts:['Ordre et opérations','Encadrements','Valeur absolue','Intervalles'], lessons:['Règles de comparaison','Encadrer une somme et un produit','Valeur absolue','Problèmes'] },
  { id:'droite-plan', semester:1, title:'Droite dans le plan', short:'Repères et équations', duration:80, objective:'Déterminer et exploiter l’équation d’une droite.', prerequisite:'Calcul vectoriel', concepts:['Repère du plan','Vecteur directeur','Équation cartésienne','Positions relatives'], lessons:['Coordonnées','Équation de droite','Parallélisme','Intersection de droites'] },
  { id:'polynomes', semester:1, title:'Polynômes', short:'Opérations et factorisation', duration:85, objective:'Calculer, factoriser et chercher les racines d’un polynôme.', prerequisite:'Calcul littéral', concepts:['Degré et coefficients','Opérations','Identités remarquables','Racines et factorisation'], lessons:['Vocabulaire','Opérations','Racines','Factorisation'] },
  { id:'equations-systemes', semester:1, title:'Équations, inéquations et systèmes', short:'Résoudre dans R', duration:95, objective:'Résoudre et interpréter équations, inéquations et systèmes.', prerequisite:'Ordre dans R · Polynômes', concepts:['Équations produit/quotient','Tableaux de signes','Inéquations','Systèmes 2×2'], lessons:['Équations','Signes et inéquations','Systèmes linéaires','Problèmes'] },
  { id:'trigonometrie-calcul', semester:1, title:'Trigonométrie 1', short:'Calcul trigonométrique', duration:70, objective:'Calculer avec les angles orientés et les rapports trigonométriques.', prerequisite:'Géométrie du collège', concepts:['Cercle trigonométrique','Radian','Sinus et cosinus','Relations fondamentales'], lessons:['Angles orientés','Cercle trigonométrique','Valeurs remarquables','Calculs'] },
  { id:'trigonometrie-equations', semester:2, title:'Trigonométrie 2', short:'Équations et inéquations', duration:75, objective:'Résoudre des équations et inéquations trigonométriques simples.', prerequisite:'Trigonométrie 1', concepts:['Équations trigonométriques','Périodicité','Inéquations sur le cercle','Solutions générales'], lessons:['Équations de base','Solutions sur un intervalle','Inéquations','Entraînement'] },
  { id:'fonctions', semester:2, title:'Généralités sur les fonctions', short:'Variations et représentations', duration:90, objective:'Étudier domaine, parité, variations et courbe d’une fonction.', prerequisite:'Équations et ordre', concepts:['Domaine de définition','Image et antécédent','Parité','Sens de variation'], lessons:['Définir une fonction','Lire une courbe','Parité','Variations'] },
  { id:'transformations-plan', semester:2, title:'Transformations du plan', short:'Translation, symétrie, rotation', duration:65, objective:'Reconnaître et construire les transformations usuelles.', prerequisite:'Calcul vectoriel', concepts:['Translation','Symétrie centrale','Symétrie axiale','Rotation'], lessons:['Translations','Symétries','Rotations','Compositions simples'] },
  { id:'produit-scalaire', semester:2, title:'Produit scalaire', short:'Orthogonalité et distances', duration:80, objective:'Calculer un produit scalaire et résoudre des problèmes métriques.', prerequisite:'Calcul vectoriel · Trigonométrie', concepts:['Définition géométrique','Formule analytique','Orthogonalité','Applications métriques'], lessons:['Produit scalaire','Calcul en coordonnées','Orthogonalité','Applications'] },
  { id:'geometrie-espace', semester:2, title:'Géométrie dans l’espace', short:'Plans et droites de l’espace', duration:85, objective:'Étudier positions relatives, parallélisme et orthogonalité.', prerequisite:'Géométrie du plan', concepts:['Droites et plans','Positions relatives','Parallélisme','Orthogonalité'], lessons:['Représenter l’espace','Positions relatives','Parallélisme','Orthogonalité'] },
  { id:'statistiques', semester:2, title:'Statistiques', short:'Séries et dispersion', duration:60, objective:'Résumer et interpréter une série statistique.', prerequisite:'Calcul numérique', concepts:['Effectifs et fréquences','Moyenne et médiane','Quartiles','Écart-type'], lessons:['Organiser les données','Indicateurs de position','Dispersion','Interprétation'] }
]

export const courses: Course[] = raw.map((course, index) => ({
  ...course, order:index + 1,
  videoUrl: yt(`${course.title} Tronc Commun Sciences Maroc mathématiques cours français`)
}))

export const getCourse = (id: string) => courses.find(course => course.id === id) ?? courses[0]
